import express from 'express';
import { ecosystemAuthMiddleware } from '../middleware/auth.js';
import { checkSubscriptionStatus } from '../../services/subscription.service.js';
import { PLATFORMS } from '../../config/plans.js';
import { createCashfreeOrder } from '../../services/cashfree.service.js';
import { Order } from '../../db/models/Order.js';

const router = express.Router();

// Apply Ecosystem Secret Key protection to all ecosystem endpoints
router.use(ecosystemAuthMiddleware);

/**
 * Check if a user has active premium status for a platform
 * GET /api/v1/ecosystem/subscription?user_id=123456789&platform_id=UNIVORA_HUB
 */
router.get('/subscription', async (req, res) => {
  try {
    const { user_id, platform_id } = req.query;

    if (!user_id || !platform_id) {
      return res.status(400).json({
        status: 'error',
        message: 'Missing user_id or platform_id query parameters.'
      });
    }

    const sub = await checkSubscriptionStatus(String(user_id), String(platform_id));

    return res.json({
      status: 'success',
      data: sub
    });
  } catch (err) {
    console.error('❌ Error in /ecosystem/subscription:', err);
    return res.status(500).json({ status: 'error', message: err.message });
  }
});

/**
 * List all configured platforms & plans
 * GET /api/v1/ecosystem/platforms
 */
router.get('/platforms', (req, res) => {
  return res.json({
    status: 'success',
    data: PLATFORMS
  });
});

/**
 * Option 1: Gateway Server Flow
 * Creates a Cashfree checkout link natively requested by a Target Bot
 * POST /api/v1/ecosystem/create-checkout
 */
router.post('/create-checkout', async (req, res) => {
  try {
    const { targetBot, userId, planId, amount, callbackUrl, customerPhone, customerEmail } = req.body;
    
    if (!targetBot || !userId || !planId || !amount || !callbackUrl) {
      return res.status(400).json({ status: 'error', message: 'Missing required parameters' });
    }

    const orderId = `ecosystem_txn_${Date.now()}_${Math.floor(Math.random() * 10000)}`;

    const cfResponse = await createCashfreeOrder({
      orderId,
      amount,
      customerId: userId,
      customerPhone: customerPhone || '9876543210',
      customerEmail: customerEmail || 'user@univora.com'
    });

    if (!cfResponse.success) {
      return res.status(500).json({ status: 'error', message: 'Cashfree session failed' });
    }

    // Save gateway order in Database
    const newOrder = new Order({
      orderId,
      telegramId: String(userId),
      platformId: targetBot,
      planId,
      amount,
      durationDays: 30, // Could be dynamic if passed
      paymentSessionId: cfResponse.paymentSessionId,
      paymentLink: cfResponse.paymentLink,
      isGatewayOrder: true,
      targetBot,
      callbackUrl
    });
    
    await newOrder.save();

    return res.json({
      status: 'success',
      data: {
        orderId,
        checkoutUrl: cfResponse.paymentLink
      }
    });

  } catch (err) {
    console.error('❌ Error creating checkout link:', err);
    return res.status(500).json({ status: 'error', message: err.message });
  }
});

/**
 * Option 2: Ticket Protocol Flow
 * Target bot verifies and claims a ticket generated by Payment Bot
 * POST /api/v1/ecosystem/verify-ticket
 */
router.post('/verify-ticket', async (req, res) => {
  try {
    const { ticketId, platformId, telegramId } = req.body;
    
    if (!ticketId || !platformId || !telegramId) {
      return res.status(400).json({ status: 'error', message: 'Missing required parameters' });
    }

    const { Ticket } = await import('../../db/models/Ticket.js');

    const ticket = await Ticket.findOne({ ticketId });
    if (!ticket) {
      return res.status(404).json({ status: 'error', message: 'Invalid ticket ID' });
    }

    if (ticket.status === 'USED') {
      return res.status(400).json({ status: 'error', message: 'This ticket has already been claimed' });
    }

    if (ticket.platformId !== platformId) {
      return res.status(400).json({ status: 'error', message: `Ticket is for ${ticket.platformId}, not ${platformId}` });
    }

    // Burn the ticket (One-Time-Use logic)
    ticket.status = 'USED';
    ticket.claimedAt = new Date();
    await ticket.save();

    return res.json({
      status: 'success',
      data: {
        planId: ticket.planId,
        orderId: ticket.orderId,
        telegramId: ticket.telegramId
      }
    });

  } catch (err) {
    console.error('❌ Error verifying ticket:', err);
    return res.status(500).json({ status: 'error', message: err.message });
  }
});

export default router;
